Add Proxy Module, Setup Pipeline, Fix Project Dependency to NetStandard2.0
PowerShell/ThreadJob pull request #42
Opened 2024-10-04 18:03 UTC by jshigetomi

# PR Summary

This pull request introduces several significant changes to the build and configuration files to support a new proxy module and improve build automation. The most important changes include updates to the build script, new pipeline configurations, and enhancements to the module packaging process.

### Build and Configuration Updates:

* [`build.ps1`](diffhunk://#diff-3258bc4162690adead72c70b672093e68c92e86a4628148f0015d61738f21b5aL25-R37): Added support for `netstandard2.0` framework and introduced variables for proxy module paths and directories. [[1]](diffhunk://#diff-3258bc4162690adead72c70b672093e68c92e86a4628148f0015d61738f21b5aL25-R37) [[2]](diffhunk://#diff-3258bc4162690adead72c70b672093e68c92e86a4628148f0015d61738f21b5aL56-R58) [[3]](diffhunk://#diff-3258bc4162690adead72c70b672093e68c92e86a4628148f0015d61738f21b5aR78)
* [`buildtools.psm1`](diffhunk://#diff-e5f95624885b01cb1c018abc33533619baf64c802d94deb4c35fd39bee1c5a02L5-R5): Switched from `PowerShellGet` to `Microsoft.PowerShell.PSResourceGet` and updated the `Publish-ModulePackage` function to handle proxy modules. [[1]](diffhunk://#diff-e5f95624885b01cb1c018abc33533619baf64c802d94deb4c35fd39bee1c5a02L5-R5) [[2]](diffhunk://#diff-e5f95624885b01cb1c018abc33533619baf64c802d94deb4c35fd39bee1c5a02R39) [[3]](diffhunk://#diff-e5f95624885b01cb1c018abc33533619baf64c802d94deb4c35fd39bee1c5a02R73-R94)
* [`doBuild.ps1`](diffhunk://#diff-cb0af1f3414f4accff3ed02d51fca351cf7f2a2f0cbbf348b5a192a548da6a86R16-R19): Enhanced build process to handle proxy module files and added support for different operating systems. [[1]](diffhunk://#diff-cb0af1f3414f4accff3ed02d51fca351cf7f2a2f0cbbf348b5a192a548da6a86R16-R19) [[2]](diffhunk://#diff-cb0af1f3414f4accff3ed02d51fca351cf7f2a2f0cbbf348b5a192a548da6a86R28-R32) [[3]](diffhunk://#diff-cb0af1f3414f4accff3ed02d51fca351cf7f2a2f0cbbf348b5a192a548da6a86R55-R67) [[4]](diffhunk://#diff-cb0af1f3414f4accff3ed02d51fca351cf7f2a2f0cbbf348b5a192a548da6a86L63-R96)

### Pipeline Configuration:

* [`.pipelines/threadjobs-official.yml`](diffhunk://#diff-d98dc37b717f8d177e226a174c6299ef8a6f5a8aca90a8c12e38b238cae90e21R1-R248): Added a new pipeline configuration for building and publishing the ThreadJob module, including steps for signing and packaging.

### Dependency Management:

* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R1-R16): Configured Dependabot to manage dependencies for NuGet and GitHub Actions.
* [`nuget.config`](diffhunk://#diff-dbd515845a90a91f83cd2dbcdf41150bff6a75806900384a44afb1f0650d9cc9L5-L9): Updated NuGet configuration to use the PowerShellCore public packages feed.

### Miscellaneous:

* [`.config/tsaoptions.json`](diffhunk://#diff-5087085f56036da072ca64127f12fef07158982e2572f4e072dfce97bba799e2R1-R8): Added configuration options for TSA tools like CredScan, PoliCheck, and BinSkim.
* [`global.json`](diffhunk://#diff-8df3cd354bc584349d04ad5675b33c042d8b99b741b8b95af394c55e0f5001bfR1-R6): Specified the .NET SDK version to ensure consistent builds.
* [`src/Microsoft.PowerShell.ThreadJob.psd1`](diffhunk://#diff-3f9e68f33eaac0cf1ad13cf39e360b712074d8ded4c2d46b86b2097ca534b3a2L11-R11): Updated module version to `2.2.0`.
* [`package.config.json`](diffhunk://#diff-df64a2a617eea2e9a1eda8d51b6e423251655e7e5d4763566ef5986821aef35cR3): Added configuration for the proxy module.

## PR Context

2024-10-09 04:52 UTC, daxian-dbw reviewed
Share my comments early. I will review the `Microsoft.PowerShell.ThreadJob.cs` tomorrow.

2024-10-09 15:16 UTC, jshigetomi commented on .github/dependabot.yml
> +      interval: daily
done

2024-10-09 15:16 UTC, jshigetomi commented on .gitignore
> +**/*.sln
done

2024-10-09 15:39 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Write-Verbose -Verbose ((Get-Item $(Build.SourcesDirectory)).FullName)
Yes

2024-10-09 15:48 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              customVersion: $(package.version)
The following is in the pwsh task and sets version:
```powershell
$manifestData = Import-PowerShellDataFile -Path src/Microsoft.PowerShell.ThreadJob.psd1
$moduleVersion = $manifestData.ModuleVersion
Write-Host "##vso[task.setvariable variable=version;isOutput=true]$moduleVersion"
```
Then the pwsh task is named package
```yaml
name: package
```
So to access version, its using the task name as a prefix.

2024-10-09 15:49 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Write-Verbose -Verbose ((Get-Item $(Build.SourcesDirectory)).FullName)
yes

2024-10-09 15:57 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Write-Host "##vso[task.setvariable variable=nupkgversion;isOutput=true]$nupkgVersion"
This is a relic of the pipeline I copied.

2024-10-09 16:08 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              archiveFile: out/ThreadJob-v$(package.version).zip
Origins of package.version answered above.

Yes that is true! I need to update the versioning!

Two different versionings in pipeline updated.

2024-10-09 16:14 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Publish-PSResource -ApiKey $env:GalleryPAT -Repository PSGallery -Path $(Pipeline.Workspace)/Microsoft.PowerShell.ThreadJob
Maybe? Do you think this needs to be changed?

2024-10-09 19:15 UTC, daxian-dbw requested changes

2024-10-09 19:18 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                object enforceValue = enforce.GetValue(null);
actually, we should get the required `MethodInfo` and the value of `SystemEnforcementMode.Enforce` in the static constructor of this type, so we do the reflection only once per process.

2024-10-09 19:55 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Publish-PSResource -ApiKey $env:GalleryPAT -Repository PSGallery -Path $(Pipeline.Workspace)/Microsoft.PowerShell.ThreadJob
Looking into this and testing if Publish-PSResource will do the trick.
I think I will need to use the NugetCommand task anyway.

2024-10-09 19:57 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Test-ModuleManifest -Path $(Pipeline.Workspace)/ThreadJob/ThreadJob.psd1
That is to test and confirm the dependency in ThreadJob.psd1 and check that Microsoft.PowerShell.ThreadJob is installed on the machine.

2024-10-11 16:36 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Write-Host "##vso[task.setvariable variable=nupkgversion;isOutput=true]$nupkgVersion"
removed unnecessary lines

2025-02-10 17:47 UTC, jshigetomi commented on doBuild.ps1
> +    Write-Verbose -Verbose -Message "Module output file path: '$ProxyOutPath'"
done

2025-02-10 17:49 UTC, jshigetomi commented on buildtools.psm1
> +    $artifactPath = Resolve-Path -Path $artifactPath
removed Resolve-Path line

2025-02-10 17:51 UTC, jshigetomi commented on build.ps1
>  )
removed Signed paramter

2025-02-10 17:52 UTC, jshigetomi commented on nuget.config
> +    <!-- Please verify that the feed below exists for your project and replace placeholder values. You may also use another feed of your choice. -->
removed

2025-02-10 17:52 UTC, jshigetomi commented on nuget.config
> +</configuration>
done

2025-02-10 17:53 UTC, jshigetomi commented on src/ThreadJob/ThreadJob.psd1
> +RootModule = '.\ThreadJob.psm1'
done

2025-02-10 17:54 UTC, jshigetomi commented on src/ThreadJob/ThreadJob.psd1
> +Description = 'ThreadJob module has been renamed to Microsoft.PowerShell.ThreadJob.'
done, tag sean

2025-02-10 17:54 UTC, jshigetomi commented on src/ThreadJob/ThreadJob.psd1
> +}
done

2025-02-10 17:54 UTC, jshigetomi commented on src/ThreadJob/ThreadJob.psm1
> +Export-ModuleMember -Alias Start-ThreadJob, ThreadJob\Start-ThreadJob
done

2025-02-10 17:57 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +using System.Diagnostics;
done

2025-02-10 17:59 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
>              if (Environment.OSVersion.Platform.ToString().Equals("Win32NT", StringComparison.OrdinalIgnoreCase))
done

2025-02-10 18:00 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                object enforceValue = enforce.GetValue(null);
done

2025-02-10 18:01 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                bool enforceLockdown = lockdownPolicy.Equals(enforceValue);
done

2025-02-10 18:02 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                    enforceLockdown = lockdownPolicy.Equals(enforceValue);
done

2025-02-10 18:03 UTC, jshigetomi commented on global.json
> +
done

2025-02-10 18:05 UTC, jshigetomi commented on buildtools.psm1
> -    if (! $Signed.IsPresent) {
done

2025-02-10 18:17 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Write-Verbose -Verbose ((Get-Item $(Build.SourcesDirectory)).FullName)
fixed

2025-02-10 18:25 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Publish-PSResource -ApiKey $env:GalleryPAT -Repository PSGallery -Path $(Pipeline.Workspace)/Microsoft.PowerShell.ThreadJob
changed

2025-02-10 18:37 UTC, jshigetomi commented on build.ps1
> +$script:ProxyOutDirectory = $config.BuildOutputPath
nope. deleted

2025-02-10 18:38 UTC, jshigetomi commented on doBuild.ps1
> +            Write-Verbose -Verbose -Message $outResults
This was used to determine where the files were being placed on the pipeline machines. I want to keep it here for now as a debug measure

2025-02-11 17:49 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> -            base.SetJobState(jobState, reason);
This bug hasn't been fixed yet. However, I wrote up a workaround using reflection. I will wait to release this until we have to.

2025-02-11 23:32 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              files_to_sign: "**/*.nupkg"
Onebranch uploaded all build artifacts to the artifact directory because I didn't do it explicitly.
Now I do it explicitly.
I only need to nupkg to upload to the gallery so I removed unnecessary .zip files and other build artifacts.

2025-02-11 23:40 UTC, jshigetomi commented on .pipelines/threadjobs-official.yml
> +              Install-Module -Repository CFS -Name Microsoft.PowerShell.PSResourceGet -MinimumVersion 1.0.5 -ErrorAction Continue -Force
Now that we are installing pwsh through the PowerShelPackagesOfficial Pipeline I can grab the latest version of pwsh which has the latest PSResourceGet in box. So this is no longer necessary.

2025-02-13 23:37 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                MethodInfo getSystemLockdownPolicy = systemPolicy.GetMethod("GetSystemLockdownPolicy", BindingFlags.Public | BindingFlags.Static);
Ideally, we should only get the `MethodInfo` with reflection once and cache it (in the static constructor of the `ThreadJob` class), then use the cached `MethodInfo` object here, so that we don't repeatedly doing the reflection operations to get the method info.

2025-02-13 23:37 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +            MethodInfo s_setJobStateDelegate = typeof(Job2).GetMethod(
Same here, should be cached in the static constructor.

2025-02-18 19:59 UTC, jshigetomi commented on nuget.config
> -  </disabledPackageSources>
done

2025-02-18 20:46 UTC, jshigetomi commented on doBuild.ps1
> +                # throw "Expected binary was not created: $BuildSrcPath/${ModuleName}.dll"
removed comment. I think it was a temporary thing

2025-02-18 20:47 UTC, jshigetomi commented on src/Microsoft.PowerShell.ThreadJob.psd1
> -HelpInfoURI = 'https://go.microsoft.com/fwlink/?linkid=2113345'
Because the link does not work

2025-02-18 20:47 UTC, jshigetomi commented on src/ThreadJob/ThreadJob.psd1
> +ModuleVersion = '2.0.4'
changed

2025-02-18 20:57 UTC, jshigetomi commented on src/ThreadJob/ThreadJob.psm1
> +Set-Alias -Name ThreadJob\Start-ThreadJob -Value Microsoft.PowerShell.ThreadJob\Start-ThreadJob
removed second alias

2025-02-18 21:09 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                    MethodInfo[] methods = systemPolicy.GetMethods(BindingFlags.Public | BindingFlags.Static);
removed

2025-02-18 22:08 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                MethodInfo getSystemLockdownPolicy = systemPolicy.GetMethod("GetSystemLockdownPolicy", BindingFlags.Public | BindingFlags.Static);
done

2025-02-18 22:08 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +            MethodInfo s_setJobStateDelegate = typeof(Job2).GetMethod(
done

2025-02-19 00:51 UTC, daxian-dbw commented on src/Microsoft.PowerShell.ThreadJob.psd1
> -HelpInfoURI = 'https://go.microsoft.com/fwlink/?linkid=2113345'
Please check with @sdwheeler on this URL. He should be able to provide a useable one.

2025-02-19 01:16 UTC, daxian-dbw requested changes

2025-02-19 01:16 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +        private static readonly FieldInfo enforce;
There is no point caching those values. They will not be used again. For `FieldInfo enforce`, instead we should cache the value of `object enforceValue`.

2025-02-19 01:16 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                null);
Those reflection work should only be done on Windows platform.

2025-02-19 01:18 UTC, daxian-dbw commented
There is test available at https://github.com/PowerShell/ThreadJob/tree/master/test, but there is no test run for this PR. Did you run test privately to verify the changes? Are you going to setup CIs for this repo?

2025-02-19 14:23 UTC, sdwheeler commented
@jshigetomi @daxian-dbw if the module is being renamed, shouldn't the PSD1 and PSM1 files be renamed?

2025-02-19 14:33 UTC, sdwheeler commented on src/Microsoft.PowerShell.ThreadJob.psd1
> -HelpInfoURI = 'https://go.microsoft.com/fwlink/?linkid=2113345'
Use this for the HelpInfoUri for Microsoft.PowerShell.ThreadJob https://go.microsoft.com/fwlink/?linkid=2305300.

2025-02-19 21:58 UTC, jshigetomi commented on src/Microsoft.PowerShell.ThreadJob.psd1
> -HelpInfoURI = 'https://go.microsoft.com/fwlink/?linkid=2113345'
added

2025-02-19 22:03 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
>          private string _currentLocationPath;
done

2025-02-19 22:04 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +        private static readonly MethodInfo s_setJobStateDelegate;
done

2025-02-19 22:06 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                null);
done

2025-02-19 22:06 UTC, daxian-dbw commented
@sdwheeler There are 2 .psd1 files, one for the ThreadJob module (a proxy module after this change) and one for the M.P.ThreadJob. The former one is under `src/ThreadJob` and the latter is under 'src'.

2025-02-19 22:07 UTC, daxian-dbw commented
> Yes I run the tests locally to verify all changes. 

That's great to know. Did you run it on Linux? Given it's for all platforms, we should run tests at least on Linux too.

2025-02-19 22:12 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +        private static readonly FieldInfo enforce;
done

2025-02-19 22:13 UTC, jshigetomi commented
> > Yes I run the tests locally to verify all changes.
> 
> That's great to know. Did you run it on Linux? Given it's for all platforms, we should run tests at least on Linux too.

I haven't run it on Linux. I will start doing that locally until I make the CI

2025-02-19 22:49 UTC, jshigetomi commented on src/ThreadJob/ThreadJob.psd1
> +AliasesToExport = @('Start-ThreadJob', 'ThreadJob\Start-ThreadJob')
Works with invocation and tab completion

2025-02-20 00:38 UTC, jshigetomi commented
@daxian-dbw Latest changes were tested on linux and windows. Some tests need to be tweaked for Linux

2025-02-21 00:33 UTC, daxian-dbw requested changes

2025-02-21 00:33 UTC, daxian-dbw commented on src/Microsoft.PowerShell.ThreadJob.psd1
> +        HelpInfoURI = 'https://go.microsoft.com/fwlink/?linkid=2305300'
This key is at top level, not in the `PrivateData`.

2025-02-21 00:33 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +        private static readonly FieldInfo s_enforce;
This one doesn't need to be cached. It's used only once.

2025-02-21 00:33 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +        private static readonly MethodInfo s_setJobStateDelegate;
nitpick: let's rename this member to be `s_setJobState`.

2025-02-21 00:33 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +            }
Add a new line to make it more readable.
```suggestion
            }

```

2025-02-21 00:33 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                    null);
Please fix the indentation here.
```suggestion
            s_setJobStateDelegate = typeof(Job2).GetMethod(
                "SetJobState",
                BindingFlags.Instance | BindingFlags.NonPublic,
                binder: null,
                new Type[] { typeof(JobState), typeof(Exception) },
                modifiers: null);
```

2025-02-21 00:33 UTC, daxian-dbw commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +using System.Runtime.InteropServices;
Can you please check if `OperatingSystem.IsWindows()` can be used in the project? If so, you can replace `RuntimeInformation.IsOSPlatform(OSPlatform.Windows)` with `OperatingSystem.IsWindows()` to make the check more concise and remove this using directive.

2025-02-21 21:49 UTC, jshigetomi commented on src/Microsoft.PowerShell.ThreadJob.psd1
> +        HelpInfoURI = 'https://go.microsoft.com/fwlink/?linkid=2305300'
I moved it back.

2025-02-21 21:50 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +        private static readonly MethodInfo s_setJobStateDelegate;
done

2025-02-21 21:51 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +        private static readonly FieldInfo s_enforce;
done

2025-02-21 21:51 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +            }
done

2025-02-21 21:51 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +                    null);
done

2025-02-21 21:53 UTC, jshigetomi commented on src/code/Microsoft.PowerShell.ThreadJob.cs
> +using System.Runtime.InteropServices;
I'm getting OperatingSystem does not contain a definition for IsWindows()

2025-02-21 23:30 UTC, daxian-dbw approved these changes

2025-02-24 18:44 UTC, merged